#importamos la imagen base de python
FROM python:3.12-slim

#Crear carpeta de trabajo
WORKDIR /app

#copiar requerimientos 
COPY requirements.txt .

#instalar requerimientos
RUN pip install --no-cache-dir -r requirements.txt

#Copiar archivo del API
COPY ./app ./app

#Exponer puerto
EXPOSE 5000

#Comando para ejecutar FASTAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]